### ISSUE TITLE
Bottom of screen not in range of rectangle capture

### ISSUE THREAD

**Issue by Zenmai0822** [ShareX/ShareX#1338]
Currently using Win7 SP1 64bit on a VM. Bottom of screen is not shaded and cannot be selected using mouse button.
![screen shot 2016-02-20 at 10 50 26](https://cloud.githubusercontent.com/assets/5943674/13197580/cceecf28-d7bf-11e5-8f32-526705171ea9.png)

**Comment by Jaex** [comment]
Are you using latest ShareX version?

**Comment by Zenmai0822** [comment]
Yes, 10.6.1.

**Comment by Jaex** [comment]
Not sure why it happens. Maybe only happens in VM?

**Comment by Zenmai0822** [comment]
Seems like yes... I tried on my Win10 (native) and it does not have this issue.

**Comment by eai04191** [comment]
Hi I have same problem too. This is a problem that exists from a long time ago (at least more than half a year ago)
now on ShareX 10.7 Release Windows 8.1 Pro(Not VM)

**Comment by Jaex** [comment]
Long time ago it was exist and I could reproduce it too and after fix it many people was reported it is fixed. Now I never managed to reproduce it after that day. And without be able to reproduce it I can't find why it happens to very few people (otherwise countless people would have reported it).

**Comment by nosvn** [comment]
11.4.1 portable exist, win7 x64

**Comment by sysilion** [comment]
i've same error reproduce in win7, win10
there system using intel hd graphic series. (skylake, ivybridge)

**Comment by caoyuz** [comment]
12.0.0 exist, win10 x64, 1920*1080
I can only select top 996 pixels
![2017-12-12_09-12-19](https://user-images.githubusercontent.com/23095894/33862257-c6270be0-df1c-11e7-9b58-be075acb23c7.jpg)

**Comment by ZeroGravity83** [comment]
@caoyuz  I'm on 12.0 and have the same problem too. For me, I can only select top 914 pixels.
I wrote more details about this issue here
https://github.com/ShareX/ShareX/issues/1800#issuecomment-351623884

**Comment by Jaex** [comment]
It is already fixed: https://getsharex.com/docs/dev-builds

**Comment by yishalee** [comment]
@Jaex  Hi this issue still occurs on Win7-64bit. On the desk screen I can only capture 997 pixels in height. 
![2018-01-30_10-30-50](https://user-images.githubusercontent.com/35944094/35545222-f6c77680-0565-11e8-84fe-4d6fcc1e3a93.jpg)

Besides, I there seems no pre-release update option as is instructed on https://getsharex.com/docs/dev-build in application settings.
![sharex_2018-01-30_10-22-22](https://user-images.githubusercontent.com/35944094/35545279-3aa00bf6-0566-11e8-933e-c612b57984c6.jpg)
Thank you.

**Comment by Jaex** [comment]
That option only exists in desktop build. You can't install it on Steam or Windows Store.
