### ISSUE TITLE
Support for PrivateBin

### ISSUE THREAD

**Issue by twiddern** [ShareX/ShareX#2067]
Hi,

It would be cool to see support for an PrivateBin environment. 
Doc: https://github.com/PrivateBin/PrivateBin/wiki/API

**Comment by YuriyZaletskyy** [comment]
Can you describe a bit more? you need all api used alltogether?

**Comment by neomodern** [comment]
Creating a new paste and adding the picture/video as an attachment would be awesome.

Here's a [public instance](https://snip.dssr.ch/) that has the file attachment feature.

**Comment by Scrxtchy** [comment]
You'd need something to create the correct encryption
here's two data objects from request parameters

```json
{"iv":"jV49wtfQSvEu57eRMEsRAQ==","v":1,"iter":1000,"ks":256,"ts":128,"mode":"gcm","adata":"","cipher":"aes","salt":"csEc6wm6cCE=","ct":"5Oc9E5FfpHh8PQ1Utd1F1dek3p6RWczj+Y8+B3WHxdeLYonaDPojEA=="}
```
```json
{"iv":"MpFZRBcPmosU3zA+a37zeg==","v":1,"iter":1000,"ks":256,"ts":128,"mode":"gcm","adata":"","cipher":"aes","salt":"F3+MJw+wq/s=","ct":"MvcQo4doo6BtclXvXygqgoPMHnYuxHjK9Z2v3PlBAJd7J4ewXsR8WA=="}
```
as you can see, the iv and ct keys both have values in base64, as well as a salt, all of which are seemingly random.
The ct is based from the content of the paste/file/filename
Uploading a file shouldn't be too hard as it's just two more json objects to put into the POST request, they both follow the same structure as our data object

**Comment by KiraSokolov** [comment]
upd

**Comment by jingofett** [comment]
I would love just the text upload, if possible

**Comment by rojnwa** [comment]
Any updates on this? Would love to be able to use PrivateBin with ShareX

**Comment by silentshotghost** [comment]
Yes privatebin.net for sharex would be nice or even one of the alternatives 
https://github.com/PrivateBin/PrivateBin/wiki/PrivateBin-Instances-Directory

**Comment by Jaex** [comment]
> Any updates on this? Would love to be able to use PrivateBin with ShareX

I wanted to implement PrivateBin but implementing client side encrypted uploaders not easy and I don't have enough knowledge about these stuffs. So I can't add it to ShareX.

**Comment by Kos9078** [comment]
Yesterday I implemented PrivateBin integration in current version of master branch. Now I'm working on settings window for it...

**Comment by Fooughhy** [comment]
I know this is an old thread, but PrivateBin still isn't implemented in ShareX, right?

**Comment by neldonado** [comment]
Any chance support for privatebin will be added?

**Comment by alexdelprete** [comment]
@Jaex has PR #6524 been merged or there were issues with it?

**Comment by Benno1308** [comment]
Push

**Comment by jpotter23** [comment]
Another vote for PrivateBin support

**Comment by JasonSanDiego** [comment]
@Jaex PR #6524 was closed by the stale bot. I assume at this point you would want it to be reviewed and re-tested before merging. I've never compiled ShareX before, but I'm willing to spend the time to figure it out and validate the code if you're open to merging it. I won't do that work if you're really not interested in merging it regardless (which would be disappointing IMO but totally your choice as the maintainer).

What do you think?

**Comment by ok-coder1** [comment]
Closed by #8344.

**Comment by BrycensRanch** [comment]
> Closed by [#8344](https://github.com/ShareX/ShareX/pull/8344).

*Patiently awaits Jaex to close issue*
