### ISSUE TITLE
Exception in Newtonsoft.Json

### ISSUE THREAD

**Issue by mrexodia** [ShareX/ShareX#2398]
Today Imgur is sort of down (gives 400 for everything) but ShareX crashes in an exception even though I have configured it to retry with a different host in the settings...

Contact me privately if you are interested in the Fiddler sessions (they contain API keys so I won't post them publicly).

Log:

```
2017-04-01 00:02:30.061 - ShareX 11.6
2017-04-01 00:02:30.061 - Personal path: C:\Users\Admin\Documents\ShareX
2017-04-01 00:02:30.061 - Operating system: Windows 8.1 Pro
2017-04-01 00:02:30.061 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2017-04-01 00:02:30.061 - Flags: SilentRun
2017-04-01 00:02:30.061 - Build: Release
2017-04-01 00:02:30.061 - ApplicationConfig load started: C:\Users\Admin\Documents\ShareX\ApplicationConfig.json
2017-04-01 00:02:30.718 - ApplicationConfig load finished: C:\Users\Admin\Documents\ShareX\ApplicationConfig.json
2017-04-01 00:02:30.733 - UploadersConfig load started: C:\Users\Admin\Documents\ShareX\UploadersConfig.json
2017-04-01 00:02:30.733 - MainForm init started
2017-04-01 00:02:31.014 - UploadersConfig load finished: C:\Users\Admin\Documents\ShareX\UploadersConfig.json
2017-04-01 00:02:31.014 - HotkeysConfig load started: C:\Users\Admin\Documents\ShareX\HotkeysConfig.json
2017-04-01 00:02:31.046 - HotkeysConfig load finished: C:\Users\Admin\Documents\ShareX\HotkeysConfig.json
2017-04-01 00:02:31.155 - MainForm init finished
2017-04-01 00:02:31.374 - Startup time: 1352 ms
2017-04-01 00:02:31.374 - CommandLine: silent
2017-04-01 00:02:31.405 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture entire screen, Job: PrintScreen
2017-04-01 00:02:31.405 - Hotkey registered: Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
2017-04-01 00:02:31.405 - Hotkey registered: Hotkey: Alt + Print Screen, Description: Capture active window, Job: ActiveWindow
2017-04-01 00:02:31.405 - Hotkey registered: Hotkey: Shift + Print Screen, Description: Start/Stop screen recording, Job: ScreenRecorder
2017-04-01 00:02:31.405 - HotkeyManager started
2017-04-01 00:02:31.405 - WatchFolderManager started
2017-04-01 00:02:35.941 - HotkeysConfig save started: C:\Users\Admin\Documents\ShareX\HotkeysConfig.json
2017-04-01 00:02:35.941 - Hotkey triggered. Hotkey: Print Screen, Description: Capture region, Job: RectangleRegion
2017-04-01 00:02:35.942 - UploadersConfig save started: C:\Users\Admin\Documents\ShareX\UploadersConfig.json
2017-04-01 00:02:35.942 - ApplicationConfig save started: C:\Users\Admin\Documents\ShareX\ApplicationConfig.json
2017-04-01 00:02:35.947 - Executing: Capture region
2017-04-01 00:02:36.135 - UploadersConfig save successful: C:\Users\Admin\Documents\ShareX\UploadersConfig.json
2017-04-01 00:02:36.166 - HotkeysConfig save successful: C:\Users\Admin\Documents\ShareX\HotkeysConfig.json
2017-04-01 00:02:36.233 - ApplicationConfig save successful: C:\Users\Admin\Documents\ShareX\ApplicationConfig.json
2017-04-01 00:02:37.820 - Task in queue. Job: Job, Type: Image, Host: Imgur
2017-04-01 00:02:37.828 - Task status: Preparing
2017-04-01 00:02:37.844 - Image saved to file: C:\Users\Admin\Documents\ShareX\Screenshots\2017-04\chrome_2017-04-01_00-02-37.png
2017-04-01 00:02:37.844 - Upload started. Filename: chrome_2017-04-01_00-02-37.png, Filepath: C:\Users\Admin\Documents\ShareX\Screenshots\2017-04\chrome_2017-04-01_00-02-37.png
2017-04-01 00:02:38.177 - Error:
Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2017-04-01 00:02:38.208 - Exception:
Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'error'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
2017-04-01 00:02:38.208 - Upload failed. Retrying upload.
2017-04-01 00:02:38.458 - Error:
Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2017-04-01 00:02:38.458 - Exception:
Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'error'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
2017-04-01 00:02:38.458 - Task failed. Filename: chrome_2017-04-01_00-02-37.png, Errors:
Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'error'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'error'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
2017-04-01 00:02:38.473 - UploadersConfig save started: C:\Users\Admin\Documents\ShareX\UploadersConfig.json
2017-04-01 00:02:38.473 - HotkeysConfig save started: C:\Users\Admin\Documents\ShareX\HotkeysConfig.json
2017-04-01 00:02:38.473 - ApplicationConfig save started: C:\Users\Admin\Documents\ShareX\ApplicationConfig.json
2017-04-01 00:02:38.598 - UploadersConfig save successful: C:\Users\Admin\Documents\ShareX\UploadersConfig.json
2017-04-01 00:02:38.614 - HotkeysConfig save successful: C:\Users\Admin\Documents\ShareX\HotkeysConfig.json
2017-04-01 00:02:38.649 - ApplicationConfig save successful: C:\Users\Admin\Documents\ShareX\ApplicationConfig.json
2017-04-01 00:02:44.624 - ApplicationConfig save started: C:\Users\Admin\Documents\ShareX\ApplicationConfig.json
2017-04-01 00:02:44.624 - HotkeysConfig save started: C:\Users\Admin\Documents\ShareX\HotkeysConfig.json
2017-04-01 00:02:44.624 - UploadersConfig save started: C:\Users\Admin\Documents\ShareX\UploadersConfig.json
2017-04-01 00:02:44.755 - UploadersConfig save successful: C:\Users\Admin\Documents\ShareX\UploadersConfig.json
2017-04-01 00:02:44.771 - HotkeysConfig save successful: C:\Users\Admin\Documents\ShareX\HotkeysConfig.json
2017-04-01 00:02:44.802 - ApplicationConfig save successful: C:\Users\Admin\Documents\ShareX\ApplicationConfig.json

```

**Comment by dimon222** [comment]
Feels like API was changed

**Comment by DevilMayPoop** [comment]
HELLO! im having the exact same issue, everything was working fine until just recently. all attempts to fix this issue has failed. restart, reinstall, re-linking upload accounts. no luck. here is my error file too.
thanks in advance for any help!
DMP

Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'error'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'error'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by swablueme** [comment]
Same issue 403 forbidden

`

```
Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'error'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'error'.
   at Newtonsoft.Json.JsonReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
````

**Comment by Jaex** [comment]
One person who had this issue told he can't even upload image in Imgur site.

**Comment by mrexodia** [comment]
Yeah the issue I had was that it didn't seem to upload to the retry host. I had imgur selected as first retry host though so that might have been the issue...

Also I checked but the response is valid json so it shouldn't crash in the first place.

**Comment by dimon222** [comment]
Seems problem is resolved now, Imgur is working just fine.

**Comment by mrexodia** [comment]
The issue isn't solved. Again: *the issue is the JSON parsing exception not that it doesn't upload to imgur*.

**Comment by Jaex** [comment]
Because they returning wrong JSON check here: http://api.imgur.com/errorhandling

It tells:

```
    "data": {
        "error": "This method requires authentication",
        "request": "\/3\/account.json",
        "method": "GET",
    },
```

So "error" is actually string but in this case it is another object.

Also this shows there is problem in their end too: `"type":"ImgurException","exception":[]` which looks pretty invalid error?

**Comment by mrexodia** [comment]
The API is never wrong, but it might be a good idea to ping them to update their documentation. Here is a Fiddler capture that produces this error: https://mega.nz/#!vgQGxDYK!TA_OQjPtkLVY0QU_7nFx-912SVBvf6bxn8fngfUrksg

**Comment by Jaex** [comment]
90% of times they don't even return JSON when error happen. Instead they retur html with error messages in it.

**Comment by 07416** [comment]
I can't upload on the Imgur website at https://imgur.com/upload either:
`{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":{}},"request":"\/upload","method":"GET"},"success":false,"status":403}`

**Comment by swablueme** [comment]
@mrexodia @Jaex @07416 
My issue was that the disposable email had apparently been blacklisted, changing to another disposable email made it work perfectly fine :P
