### ISSUE TITLE
Blank entries in main windows' recent captures list

### ISSUE THREAD

**Issue by arusergithub** [ShareX/ShareX#4520]
This and quite a few others show blank:

![image](https://user-images.githubusercontent.com/50074375/70666776-49960880-1c67-11ea-8522-23855af2ee02.png)

even though a click confirms it is present.

**Comment by Zaczero** [comment]
Looks like a similar problem to #4510 which should be fixed by now =)

**Comment by Jaex** [comment]
Duplicate of #4510

**Comment by arusergithub** [comment]
> Looks like a similar problem to #4510 which should be fixed by now =)

The 13.0.1 (up to date) still shows the fail: 
![image](https://user-images.githubusercontent.com/50074375/71118895-e0ffdc00-21d0-11ea-93e4-702fda04043f.png)

**Comment by Jaex** [comment]
It is fixed in dev build.
