### ISSUE TITLE
FFMPEG issue

### ISSUE THREAD

**Issue by Depilitis** [ShareX/ShareX#5170]
![image](https://user-images.githubusercontent.com/69131802/98057445-2b914380-1df7-11eb-991f-15eef4bb1455.png)

This happens everytime I try to record, and the Stop/Abort buttons don't work so I click them multiple times. Then the recording stops after I close out of those.

**Comment by vaibhavpandeyvpz** [comment]
Yes. Happening same with me since I updated.

**Comment by Depilitis** [comment]
Issue is fixed since newest update.

**Comment by vaibhavpandeyvpz** [comment]
I have newest update and it's happening to me, so it's not fixed.

**Comment by vaibhavpandeyvpz** [comment]
OK. Since the author is not able to reproduce this, I would tell everyone that the solution is to turn off your anti-virus **temporarily**. I downloaded the latest update today, still ran into same issue. But just after I put avast! to keep quiet for an hour, ShareX could work as expected. So it's your anti-virus denying ShareX/FFmpeg to record screen content, maybe considering it as a potential malware.
