### ISSUE TITLE
Z-ordering bug on Windows 11 22000.100

### ISSUE THREAD

**Issue by Tropix126** [ShareX/ShareX#5712]
This is more of a heads up than a practical bug report, since W11 isnt even at the beta channel yet. It appears that the latest build has done something with window z-ordering and the screenshot overlay is now placed behind maximized windows. The overlay is only interactible on the taskbar.

![image](https://user-images.githubusercontent.com/42101043/126808080-5c7a58f0-5748-406f-98cb-246c851e4f3d.png)

**Comment by Jaex** [comment]
I don't use Windows 11 so can't test it.

**Comment by Aria-NL** [comment]
Confirming this bug - it also breaks all context menus making them appear behind windows on the desktop until the computer is restarted

**Comment by Gaz492** [comment]
> 
> 
> Confirming this bug - it also breaks all context menus making them appear behind windows on the desktop until the computer is restarted

Able to confirm this as well

**Comment by Marcuzz** [comment]
> 
> 
> Confirming this bug - it also breaks all context menus making them appear behind windows on the desktop until the computer is restarted

I can also confirm that this causes context menus and even select dropdowns in web browsers to show at the taskbar z-position. This only happens on 22000.100 and did not happen on 22000.71. 

The following is from the 22000.100 change-log, and it wouldn't surprise me if this messed it up:

> We've done some work on the context menu positioning logic so that submenus should no longer appear partially offscreen or unexpectedly far away.

**Comment by Hubza** [comment]
running into the same issue here. second i take a screenshot all the layering breaks and to fix it a restart is required

**Comment by DarkiBoi** [comment]
Able to confirm this aswell

**Comment by Lebyy** [comment]
> Confirming this bug - it also breaks all context menus making them appear behind windows on the desktop until the computer is restarted. First screenshot after reboot works correctly, then subsequent screenshots are broken,

Can confirm this.

**Comment by Jaex** [comment]
It is bug on Windows 11 side, so even if I could test it still I couldn't fix it. So you should wait for Microsoft to fix it. This problem not only happens to ShareX but also happens to other screen capture software which using fullscreen windows. But I saw people also reporting context menu of software such as browsers showing behind windows. So this Windows 11 issue affects tons of software and not a ShareX bug. This issue also looks like started right after they released latest build which proves they broken something in latest build while all software working fine in previous build.

**Comment by Absolucy** [comment]
for anyone affected by this: you can get out of it it by going to task manager with ctrl+alt+delete, then killing ShareX.exe (or whatever else may be causing it)

**Comment by MSM74588** [comment]
Facing same issue
![Screenshot 2021-07-25 184342](https://user-images.githubusercontent.com/48552989/126900460-b75f443c-dec9-4313-b6ba-5ff69cf91d86.jpg)

**Comment by Rothes** [comment]
####**To fix this with keeping computer open, open your Task Manager and kill dwm.exe.**

**Comment by axelitus** [comment]
I can confirm the workaround from @Rothes does the trick.

**Comment by MSM74588** [comment]
Unable to terminate the dwm.exe{Displayed in win11 as "Desktop Window Manager"}, Terminating it will cause win11 to shut down. I have observed that After starting a new session(after restart or turning it on) it works for the first time, but from the second time it does not work, it only can focus on the taskbar {in build 22000.100}

![image](https://user-images.githubusercontent.com/48552989/127041309-eca51f08-62fd-483e-9d87-4e48f42c2006.png)

**Comment by CadetSparklez** [comment]
you can try pressing alt tab and closing the region capture then restarting explorer.exe and sharex or logging out then back in with ctrl alt delete

**Comment by MSM74588** [comment]
The Ctrl+Alt+Delete trick worked for me

**Comment by gdude2002** [comment]
You can temporarily fix the issue either via ctrl+alt+delete or locking the PC via win+L.

I'm a developer myself so, in the event that this isn't a Windows bug specifically, I'm happy to collect anything needed for debugging. It's worth noting that the built-in Windows screenshot tool (Win + Shift + S) also uses a full-screen overlay and doesn't have this problem, so it's possible that this may be a ShareX bug.

**Comment by Tropix126** [comment]
> Unable to terminate the dwm.exe{Displayed in win11 as "Desktop Window Manager"}, Terminating it will cause win11 to shut down. I have observed that After starting a new session(after restart or turning it on) it works for the first time, but from the second time it does not work, it only can focus on the taskbar {in build 22000.100}
> 
> ![image](https://user-images.githubusercontent.com/48552989/127041309-eca51f08-62fd-483e-9d87-4e48f42c2006.png)

Killing DWM will not cause windows to shut down, it's just that dialog is extremely poorly worded.

**Comment by Redcarred2** [comment]
Able to confirm this

**Comment by nta** [comment]
I'd be inclined to believe this may be a similar underlying Windows bug to that which led to nvaccess/nvda#12648 which according to a comment on that thread is fixed in a future Windows 11 flight.

**Comment by gdude2002** [comment]
It seems like it isn't fixed yet.

![image](https://user-images.githubusercontent.com/204153/127308281-8cc0e96d-67ca-4294-ad97-4f85cced488f.png)

Still, it's definitely a Windows bug, then - guess all we need to do is wait. In the meantime, Windows' own snipping tool is passable - but sadly nowhere near up to spec with ShareX.

**Comment by gwilly10** [comment]
Looks like its just capture region that really does it. If I do a capture entire screen its fine.
I always do open image editor after task to add drawing on it before going to clipboard so really, I can crop from it directly instead.

Restarting explorer will fix too without needing elevation.
You can make a .bat with this.
taskkill /im explorer.exe /f
start explorer.exe
exit

**Comment by hazre** [comment]
Yeah, this build seems to be super buggy this time around. I second what @gwilly10 said, and restarting ShareX seems to work as well for a while before it starts bugging out again.

**Comment by axelitus** [comment]
I am not sure if it was a Windows update or a ShareX update but as of yesterday it is working perfectly fine and I no longer have to kill any process to regain functionality.

I have this Windows 11 version and experience pack if it helps anyone:
![image](https://user-images.githubusercontent.com/732441/127530478-c6b8cde6-6088-4ba1-9c82-9f806213131a.png)

**Comment by gdude2002** [comment]
I have the same build and Experience pack as the above comment, but I can't confirm this fix - I still have this issue. I have no pending ShareX updates, either.

I do have the following update pending, though - since ShareX is written in C#, it may fix the problem. Let's find out!

![image](https://user-images.githubusercontent.com/204153/127534088-150a5e39-f886-4e4b-af61-e879f7053e57.png)

**Comment by gdude2002** [comment]
Nope, no fix there either. sadge.

**Comment by 04anubhavv** [comment]
The workaround, press start then click on the taskbar

**Comment by Walker-BJ99** [comment]
Yes, I also encountered this problem on my computer, which has a certain impact on my work and games, because every time I take a picture, I need to restart the desktop window manager once, and I am worried about it will crash my program in the restarting.
But I just found out that calling out the start menu when the problem occurs may also solve the problem. You can try to experiment.

**Comment by axelitus** [comment]
I am not sure what did fix this issue, but I haven't had it again... I can take region screenshots and the context menus and even the open windows flyouts work as expected... I haven't done anything "special", just the regular updates, so I cannot pinpoint why it is working for me now...

**Comment by Puyodead1** [comment]
I've been having this issue for a few weeks now, just found this issue :(

**Comment by xavierlxvii** [comment]
As a temporary solution, locking the PC with Win+L and unlocking fixes it for 1 region screenshot.

Hopefully resolved by a windows update sometime soon.

**Comment by axelitus** [comment]
Ok, the issue is back and I am thinking that when I have previously taken some screenshots, I have been doing something that "restores" the z-ordering. (I can confirm opening the start menu fixes the ordering for me). So this issue hasn't been resolved and it was a misleading behavior I have been seeing on my computer.

**Comment by AdamAtomus** [comment]
easy way to fix it, every time you take a screenshot, just win+L (lock windows) then unlock pc with the 4 digit code.

**Comment by kingtastic** [comment]
hitting the windows key right before screenshotting works for a temporary fix

**Comment by iGerman00** [comment]
No need to lock your computer. Press Ctrl+Alt+Del to temporarily fix the triggered z-order problem. Context menus and ShareX will be broken right after you use ShareX's capture for the first time after a Ctrl+Alt+Del.

**Comment by rakion99** [comment]
i just open task manager(ctrl+shift+esc) and find windows explorer and click restart, problem "fixed" till next screenshot or bug happening again but yes this is a windows 11 bug so we need to wait for Microsoft to fix it zzzzzz
![image](https://user-images.githubusercontent.com/1360084/127787895-4808b2f3-456a-4f38-a4d1-d0cb36449732.png)

**Comment by voidel** [comment]
I've been suffering with this the last few days. Took me a while to realize that it was ShareX that was causing it.

**Comment by xavierlxvii** [comment]
> I've been suffering with this the last few days. Took me a while to realize that it was ShareX that was causing it.

It's not ShareX causing it, it's a windows 11 issue

**Comment by voidel** [comment]
> > I've been suffering with this the last few days. Took me a while to realize that it was ShareX that was causing it.
> 
> It's not ShareX causing it, it's a windows 11 issue

Semantics, really. It's an interaction between Windows 11 and ShareX that is causing it, regardless. If I stop using ShareX, the problem goes away. Looking forward to a fix on Microsoft's end then.

**Comment by CubityFirst** [comment]
I'm on Windows 11, latest build (22000.100).

I have no issues, at all, in any way on any build in any menu at all.

Region Capture works fine, After Capture works fine, the toolbar works fine.
I've tried it both on 13.5 Portable (so none of my settings would influence it at all) and on 13.5.1 Dev (pre-release because I was helping test a feature).

I can't reproduce literally any of the issues that other people are having in this thread. I'm sure they're happening, since the number of people reporting them is quite high, but I can't reproduce any of it.

**Comment by voidel** [comment]
@CubityFirst I video captured the issue in an nutshell [here](https://a.uguu.se/bXoAySPrJL8k_NrK8yXYz6e.webm)(I actually used ShareX to record the capture too 🤣)

It's not just application context menus it affects either, it's all sorts of windows context menus and popups, including taskbar peeks.

**Comment by CubityFirst** [comment]
Can't reproduce this is

> 
> 
> @CubityFirst I video captured the issue in an nutshell [here](https://a.uguu.se/bXoAySPrJL8k_NrK8yXYz6e.webm) (I actually used ShareX to record the capture too 🤣)
> 
> It's not just application context menus it affects either, it's all sorts of windows context menus and popups, including taskbar peeks.
> 
> For me it's also 100% deterministic, it always happens. Hitting CTRL+ALT+DEL and then hitting Esc seems to resolve it.

[Can't reproduce this issue either.](https://i.cubityfir.st/tL9FgHUG4J.mp4)

**Comment by voidel** [comment]
@CubityFirst Most peculiar, I have the exact same version as you.

**Comment by hazre** [comment]
I have 2 devices running windows 11 on latest build (22000.100) and one has the issue and the other doesn't. so no idea what's causing it.

**Comment by binamracode** [comment]
same issue with me

**Comment by TheChilliPL** [comment]
Happened to me. Windows tried 3 times to update to 22000.100, each time I had to uninstall the update just due to how much I use ShareX

**Comment by foxlldev** [comment]
Same issue.

**Comment by voidel** [comment]
For those that need a quick remedy to the problem, CTRL+ALT+DEL and then Esc to cancel sorts out the Z layers. I can now sort of live with it, whereas before knowing that I was having high blood pressure moments.

**Comment by addshore** [comment]
This (in PowerShell) has become my friend since switching to Windows 11 with ShareX

```
stop-process -name explorer
```

**Comment by leonidasv** [comment]
>since W11 isnt even at the beta channel yet.

And then they pushed it to the Beta channel before the fix. 🤡

**Comment by ApexioDaCoder** [comment]
Just pressing the windows key after every screenshot fixes it for me.

**Comment by Jaex** [comment]
https://blogs.windows.com/windows-insider/2021/08/05/announcing-windows-11-insider-preview-build-22000-120/

> Addressed an issue believed to be causing a number of unexpected UI issues in the previous flight, including semi-transparent and unreadable dialogs, z-ordering issues, large, shadowed areas getting stuck on the screen. and backwards text in context menus for Arabic and Hebrew Insiders.

Did they fix the issue in latest build?

**Comment by Seeker1437** [comment]
Checking it right now actually

**Comment by Seeker1437** [comment]
Seems to resolve the issue for me

**Comment by xavierlxvii** [comment]
Checking too

**Comment by voidel** [comment]
I can also confirm it has been fixed.

![winver](https://i.vgy.me/OnXisr.png)

**Comment by xavierlxvii** [comment]
Issue is resolved!

**Comment by inb40** [comment]
Cumulative Update for Windows 11 (10.0.22000.120) (KB5005188) has fixed this issue for me.

**Comment by Jaex** [comment]
Nice to hear.
