### ISSUE TITLE
Color picker crashed on second monitor

### ISSUE THREAD

**Issue by maxiv** [ShareX/ShareX#700]
When move cursor to left display, get exception:

System.ArgumentOutOfRangeException: Parameter must be positive and < Width.
Parameter name: x
   at System.Drawing.Bitmap.GetPixel(Int32 x, Int32 y)
   at ShareX.ScreenCaptureLib.RectangleRegion.get_CurrentColor()
   at ShareX.ScreenCaptureLib.RectangleRegion.DrawMagnifier(Graphics g)
   at ShareX.ScreenCaptureLib.RectangleRegion.Draw(Graphics g)
   at ShareX.ScreenCaptureLib.Surface.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Jaex** [comment]
It must be fixed now but because I don't have multi monitor without testing I can't be 100% sure.

**Comment by ar2oor** [comment]
This bug still occurs.
When i replace monitors 1-2 to 2-1 it's ok, but in my configuration 1-2 it's not working.
Color picked on left monitor takes color from right, color picked from right monitor results in error.

![201579179108](https://cloud.githubusercontent.com/assets/1141686/8658805/7eda8a2e-29a6-11e5-9cc6-eeac2dd1a887.png)
