### ISSUE TITLE
Error when opening "Image History"

### ISSUE THREAD

**Issue by 44CB7913** [ShareX/ShareX#8244]
Even after updating I am receiving this issue when opening my "Image History" - hitting continue causes it to then proceed to work however the pop-up appears everytime.

2025-11-11 13:32:21.251 - Unhandled exception:
System.ComponentModel.Win32Exception (1400): Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.TextBoxBase.CreateHandle()
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

<img width="727" height="552" alt="Image" src="https://github.com/user-attachments/assets/6528f098-a4a1-44ed-995e-bbde117aec41" />

**Comment by 44CB7913** [comment]
Additionally the functionality of search bar etc disappears

**Comment by QuAzI** [comment]
Have the same issue on Windows 11 LTSC 24H2 (Build 266100.7171), looks like on Windows 10 it was fine

**Comment by QuAzI** [comment]
2 cases with 1400 exception present in log I attached there https://github.com/ShareX/ShareX/issues/8287#issuecomment-3669776658
But at the moment I have no idea how to reproduce it right now. Maybe it was fixed when I replaced dotnet-sdk-10.0.100-win-x64.exe with dotnet-sdk-10.0.101-win-x64.exe

**Comment by Tanimodori** [comment]
Same issue with ShareX 19.0.2 and Windows 10 22H2. The functionality of search bar etc disappears too.

There are several reports here: #8250 #8150 #8225 #8099 . This is annoying and significantly affecting users. I hope that this issue to be fixed soon.

**Comment by Tanimodori** [comment]
Same Issue still exist in 20.0.2

<img width="833" height="677" alt="Image" src="https://github.com/user-attachments/assets/f94b4834-2e2a-4b9e-95ae-e372945fcef3" />

**Comment by plitgg776** [comment]
Same error exists in 21
